### PR TITLE
WIXFEAT:4149 - Add support for variables and radio buttons in thmutil, and update WixStdBA to use the new functionality.

### PR DESCRIPTION
**Pull request by rseanhall**
The title says it all.

Next steps:
1. Continue adding functionality to thmutil so WixStdBA doesn't have so many special controls.
2. Design and implement the Content idea to make it easier to have one control whose text changes depending on context.
3. Update the built-in themes.

### CODE REVIEW

**Comment by robmen** [comment]
It hurts my head that this is all one change. :)

**Comment by robmen** [comment]
@rseanhall can you confirm real quick that this change is still good to go (as a stepping stone to where we want to get). If so, I'll get it in since it's a good step in the right direction.

**Comment by rseanhall** [comment]
Yes, I still believe this is good to go.  Would you rather I send a pull request for my working branch where the commits aren't squashed? https://github.com/rseanhall/wix4/tree/feat4149incr

**Comment by rseanhall** [comment]
Superseded by #79.

**Pull request closed without merging**
