### PR TITLE
WIXFEAT4149 - Adding support to WixStdBA for displaying the message "Uninstall Successful"/"Repair Successful" after product uninstall/repair

### PR DESCRIPTION
**Pull request by PavelAnfimov**
Hello, we want you to present our "lightweight" implementation [WIXFEAT4149](http://wixtoolset.org/issues/4149/). In the discussion on the wix-devs, you have not come to a consensus, or discussing labor-intensive solutions. This implementation is easy to develop and support, because it requires minimal modifications as WixStandardBA as themes.

### CODE REVIEW

**Comment by barnson** [comment]
Are you interested in bringing this change into WiX v3.10?

**Comment by PavelAnfimov** [comment]
Yes, this is a good offer.

**Comment by barnson** [comment]
Great. Can you create a new pull request against wixtoolset/wix3/develop? That's the v3.10 branch.

**Comment by PavelAnfimov** [comment]
See https://github.com/wixtoolset/wix3/pull/188

**Comment by robmen** [comment]
We'll go a different way in v4.0 with @rseanhall's cool thmutil work. Thanks for sending this over to v3.x.

**Pull request closed without merging**
