### PR TITLE
Allow Pyro to exclude empty patch transforms

### PR DESCRIPTION
**Pull request by heaths**
Same basic code as for the wix3 repo but with all the refactoring necessary in the new model.

### CODE REVIEW

**Comment by heaths** [comment]
This has been open for a while. I rebased on top of 'develop'. The change is already in wix3, so is there anything holding back a merge into wix4? Same change, just updated to use the `PyroCommandLine` class instead.

**Comment by robmen** [comment]
IIRC, we were going to take this as a warning with no command line switch. Suppression would happen by suppressing the warning and error by promoting warnings to errors. How this was captured in a bug comment.

**Comment by heaths** [comment]
I didn't see such a comment in 4543, but now that you mention it I do recall discussing this at triage. I'll make the change and submit a new PR.

**Comment by robmen** [comment]
I think you caught a bunch of random stuff in this pull request. Can you try again from a clean branch.

**Comment by heaths** [comment]
@robmen, I got this done, but in trying to create tests it turns out the patch build tool chain is completely on the floor. So this is blocked on a bad refactoring throw `NullReferenceException`s and other issues. I've been fixing some, but the whoever refactored should probably fix and make sure the tests are in working order (the test authoring doesn't even use the right schema).

**Pull request closed without merging**
