### PR TITLE
Define variadic macros for use throughout the codebase

### PR DESCRIPTION
**Pull request by heaths**
Variadic macros can be a productivity boost by not having to think about which macro to use only to change it later when you realize you want an extra string argument...if you remember. And it's not always easy to catch when you don't remember.

This also includes a few supporting changes to libs like wcautil, where I copy the `va_list` and iterate through a copy to determine the number of arguments automatically while maintaining backward compatibility.

### CODE REVIEW

**Comment by robmen** [comment]
The use of `va_copy` seems to fail the VS2010 build:

```
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\x86_amd64\CL.exe /c /IE:\src\github\wix4\build\obj\version\ /IE:\src\github\wix4\sr
  c\libs\wcautil\inc /IE:\src\github\wix4\src\libs\wcautil /IE:\src\github\wix4\build\obj\debug\x64\wcautil\2010\ /I"C:\Program Files (x86)\Micr
  osoft SQL Server Compact Edition\v4.0\include\\" /IE:\src\github\wix4\src\libs\dutil\inc /Z7 /nologo /W4 /WX /MP /Od /D _DEBUG /D DEBUG /D WIN
  32 /D _WINDOWS /D _WIN32_MSI=500 /D _WIN32_WINNT=0x0501 /Gm- /RTC1 /MTd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Yc"precomp.h" /Fp"E:\src\git
  hub\wix4\build\obj\debug\x64\wcautil\2010\wcautil.pch" /Fo"E:\src\github\wix4\build\obj\debug\x64\wcautil\2010\\" /Fd"E:\src\github\wix4\build
  \obj\debug\x64\wcautil\2010\vc100.pdb" /Gz /TP /Zl /errorReport:queue E:\src\github\wix4\src\common\precomp.cpp -YlprecompDefine
  precomp.cpp
  C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\x86_amd64\CL.exe /c /IE:\src\github\wix4\build\obj\version\ /IE:\src\github\wix4\sr
  c\libs\wcautil\inc /IE:\src\github\wix4\src\libs\wcautil /IE:\src\github\wix4\build\obj\debug\x64\wcautil\2010\ /I"C:\Program Files (x86)\Micr
  osoft SQL Server Compact Edition\v4.0\include\\" /IE:\src\github\wix4\src\libs\dutil\inc /Z7 /nologo /W4 /WX /MP /Od /D _DEBUG /D DEBUG /D WIN
  32 /D _WINDOWS /D _WIN32_MSI=500 /D _WIN32_WINNT=0x0501 /Gm- /RTC1 /MTd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Yu"precomp.h" /Fp"E:\src\git
  hub\wix4\build\obj\debug\x64\wcautil\2010\wcautil.pch" /Fo"E:\src\github\wix4\build\obj\debug\x64\wcautil\2010\\" /Fd"E:\src\github\wix4\build
  \obj\debug\x64\wcautil\2010\vc100.pdb" /Gz /TP /Zl /errorReport:queue wcalog.cpp wcascript.cpp wcautil.cpp wcawrapquery.cpp wcawow64.cpp wcawr
  ap.cpp qtexec.cpp -YlprecompDefine
  wcalog.cpp
  wcascript.cpp
  wcautil.cpp
  wcawrapquery.cpp
  wcawow64.cpp
  wcawrap.cpp
  qtexec.cpp
wcawrap.cpp(76): error C3861: 'va_copy': identifier not found [E:\src\github\wix4\src\libs\wcautil\wcautil.vcxproj]
Done Building Project "E:\src\github\wix4\src\libs\wcautil\wcautil.vcxproj" (default targets) -- FAILED.
```

**Comment by heaths** [comment]
Indeed its not defined, but forced me to rethink and realize that `va_copy` was unnecessary anyway. Also noticed while I was at it that we could've leaked however va_start works (varies by platform - a leak may not even occur) so call `va_end` as needed after `LExit` label.

**Comment by heaths** [comment]
BTW, I was considering writing a unit test for this but it seems most of them are on the floor in wix4 so ended up writing a sample that worked as expected.

``` c++
#include <windows.h>

void test(int argc, ...)
{
    va_list args = NULL, iter = NULL;
    va_start(args, argc);

    if (-1 == argc)
    {
        LPCWSTR wz;
        argc = 0;

        iter = args;
        while (NULL != (wz = va_arg(iter, WCHAR*)) && L'\0' != *wz)
        {
            ++argc;
        }
    }

    printf("%d args:\n", argc);
    for (int i = 0; i < argc; ++i)
    {
        LPCWSTR wz = va_arg(args, WCHAR*);
        printf("arg%d = %ls\n", i, wz);
    }

    va_end(args);
    printf("\n");
}

int _tmain(int argc, _TCHAR* argv[])
{
    test(0);
    test(0, L"not printed");
    test(1, L"printed");
    test(1, L"printed", L"not printed");
    test(2, L"printed"); // arg1 = (null)
    test(2, L"printed", L"printed");
    test(-1);
    test(-1, L"printed");
    test(-1, L"printed", L"printed");
}
```

**Comment by robmen** [comment]
IIRC, @Mike-GC has been updating the dutil unit tests. I thought they work.

**Comment by heaths** [comment]
Some of them do, but this function is in wcautil. I have a few ideas how we might unit test some of those functions since most will take a product handle as well. We could also use the "wait" custom action I wrote a while back to create a session, hold it, then fail it when we're finished (or just conditioning out `RegisterProduct` may suffice). Seems like a little side project itself, though.

**Comment by robmen** [comment]
Well, wcautil never had unit tests (for reasons you point out). I guess I'm not sure what your original point about unit tests failing was about in the end then. Were you just taking a dig that many of the tests are still failing or was there something more important there that I'm missing?

**Comment by heaths** [comment]
I'm saying I didn't see the point in adding tests if they aren't all passing and, therefore, not a reliable means of detecting issues. At this point I don't know what is expected to pass or fail so how can I gauge whether or not I caused a regression apart from what dev testing I did? Or how could anyone modifying my changes later gauge the same?

I wouldn't use this forum to "dig" on anything. I would sooner use email to understand why the tests were broken in the first place.

**Comment by robmen** [comment]
Hmm. You can always add additional tests (as long as they are passing). Admittedly the failing test don't provide a clear picture but if the same tests are passing and failing before the changes and after the changes then you have _some_ confidence that things work (even better if fewer tests are failing after the changes).

If we never add tests unless all of the other tests are passing, we'll never dig out of the technical debt that has built up over many years.

**Comment by robmen** [comment]
By the way, the variadic defines are very cool. Wish we would (could?) have implemented them way back when.

**Comment by Mike-GC** [comment]
Heath - all the dutil unit tests pass for me, I do regularly run all of them whenever I modify any part of dutil. Are some of them failing for you, or is it another test that's failing?

They pass when I use this commandline (from the build\debug\x86 directory):
xunit.console.clr4.x86.exe DUtilUnitTest.dll

**Comment by heaths** [comment]
They pass when I run them manually like that. Thanks.

Seems ~\test\test.bat runs ~\test\test\All.testproj which has a lot of broken tests. Still, creating unit tests for wcautil feels like a separate project. Not opposed to it, but the test project I created for the main SUT in wcautil provided the point. :)

**Comment by robmen** [comment]
100% agree on wcautil test project being a very large effort. That was part of why I didn't understand the criticism of the tests. There never were tests for wcautil and the dutil tests pass today.

As for execution, there is the `test\test\Unit.testproj` that only runs the "fast tests". It has a bunch of Burn unit tests that fail right now but the dutil and wix unit tests are working. Eventually, hope to wire that project into the build so unit tests are automatically run with full build.

**Pull request merged**
