### PR TITLE
WIXBUG:4499 - Bind MBApreq language to correct langid

### PR DESCRIPTION
**Pull request by BMurri**
This replaces the previous pull request that was showing up as corrupted.
This is the correct fix for wix4. I will have a separate pull request for wix3 ready shortly, addressing the issues presented there.

### CODE REVIEW

**Comment by robmen** [comment]
Can you rebase this off `develop` to clean up a lot of the empty commits there?

**Comment by BMurri** [comment]
I'll try. My git-foo still leaves a little to be desired.

Sent from my Windows Phone

**Comment by BMurri** [comment]
Hope this looks cleaner

**Comment by robmen** [comment]
This pull request has been merged.

**Pull request closed without merging**
